### ISSUE TITLE
Let's not further the Google hegemony

### ISSUE THREAD

**Issue by vassudanagunta** [docbook/wiki#12]
[DocBookAlternatives](https://github.com/docbook/wiki/wiki/DocBookAlternatives) has the single line `Please google for these :)` with a Google link. How about swapping in a privacy respecting search, or at least offer both. Perhaps: 

> Please [search the web](https://duckduckgo.com/?q=docbook+alternatives) for these :)

**Comment by ndw** [comment]
Yes, totally. I generally avoid mentioning that search engine by name. Fixed.
