### ISSUE TITLE
requesting edit access

### ISSUE THREAD

**Issue by saufrecht** [docbook/wiki#13]
In particular, I want to fix WhyDocBook, which has a scrambled link that renders as:

`EXTRA! Eric Raymond tells you [Why care about DocBook at all?](http://www.xml-dev.com:8080/tldp/http://cvsview.tldp.org/index.cgi/*checkout*/LDP/howto/docbook/DocBook-Demystification-HOWTO/DocBook-Demystification-HOWTO.xml#N10037)`

and should be
`EXTRA! Eric Raymond tells you [Why care about DocBook at all?](https://tldp.org/HOWTO/DocBook-Demystification-HOWTO/x57.html)`

which renders to:

EXTRA! Eric Raymond tells you [Why care about DocBook at all?](https://tldp.org/HOWTO/DocBook-Demystification-HOWTO/x57.html)

**Comment by eduardtibet** [comment]
Thanks for notifying about this 404 issue. Fixed!
