### ISSUE TITLE
No links for CamelCased pages in https://github.com/docbook/wiki/wiki/DocBookPackages

### ISSUE THREAD

**Issue by shlomif** [docbook/wiki#14]
Hi!

The CamelCase pages mentioned in https://github.com/docbook/wiki/wiki/DocBookPackages are not linked which is inconvenient. See e.g.:

https://github.com/docbook/wiki/wiki/CygwinPackages

There may be similar issues on other pages, but AFAIK one cannot easily send pull-requests for GitHub wikis, which makes it harder for me to contribute.

**Comment by eduardtibet** [comment]
@shlomif You can require R/W access rights from @ndw , if you want to contribute actively. Ask him directly by sending private email.

**Comment by shlomif** [comment]
On Tue, 25 Aug 2020 05:51:40 -0700
Eduard Tibet <notifications@github.com> wrote:

> @shlomif You can require R/W access rights from @ndw , if you want to
> contribute actively. Ask him directly by sending private email.
> 

Thanks! I'll try that.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://shlomifishswiki.branchable.com/Self-Sufficiency/

Before I married, I had three theories about raising children and no children.
Now, I have three children and no theories.
    — https://www.brainyquote.com/quotes/john_wilmot_175259

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
OK, I was given a write permission (thanks @ndw and @eduardtibet  ) and fixed the links in that page, so I'll close the bug for now. My regex-fu to find other pages with broken links failed for now (but i can take a different approach).

**Comment by shlomif** [comment]
An update: After being given the write permission I was able to update the wiki more easily using `git push` and neovim. For the record, the vimscript "library" I wrote for this is this one (license is MIT/Expat):

```
map <F2> :s/\v<(([A-Z][a-z]*){2,})>/[\1](\1)/g<cr>
map <F3> :s#\(<c-r>/\)#[\1](\1)#<cr>
map <F4> Bv/\v([^A-Za-z]\|$)<cr>"ada[<c-r>a](<c-r>a)<esc>
let g:ackprg='ack'
Ack --sort "$(ls *.md | perl -lnE 's/\.md$//;push@x,$_;END{say "(".(join"|",@x).")"}' )" $(ls *.md | perl -lnE 'say if $_ ge "UsingX" and (!/\A[f]/)')

```

I'm aware it is very hacky.
