### ISSUE TITLE
access to docbook wiki please?

### ISSUE THREAD

**Issue by edrulrd** [docbook/wiki#16]
Please provide access to edrulrd@hotmail.com on github.

Thanks,
Ed

**Comment by ndw** [comment]
I've sent you an invitiation. Please let me know if you don't receive it. (And please close this issue if you do! :-) )

**Comment by BPowell76** [comment]
Is there not a better way to do this? Needing to request access to view a "public" wiki is counter-intuitive. I just want to be able to read the tutorial to see what using docbook is like.

**Comment by ndw** [comment]
You don't need a login to read the wiki, it's here: https://github.com/docbook/wiki/wiki

You need a login to update the wiki because otherwise spambots and malicious trolls will fill it with [expletive]. "That's why we can't have nice things."

**Comment by BPowell76** [comment]
I think my issue was related to a page not existing and so the wiki was defaulting to edit mode. I made an issue about it: https://github.com/docbook/wiki/issues/17
