### ISSUE TITLE
Requesting edit access to DocBook Wiki

### ISSUE THREAD

**Issue by bobstayton** [docbook/wiki#6]
Please add me as a collaborator for the DocBook Wiki

**Comment by eduardtibet** [comment]
Bob, I suggest you need to write PM directly to Norm (@ndw ). He has full access rights to add new members to teams.

Another way is to try this link for request: https://github.com/orgs/docbook/teams/team-wiki/teams

**Comment by ndw** [comment]
Hi @bobstayton 
I've added you to the wiki team. I also made you an "owner" of the organization, so you have complete access.
