### ISSUE TITLE
Page number prefix

### ISSUE THREAD

**Issue by bernhard-kleine** [docbook/wiki#9]
The stylesheet on that [page](https://github.com/docbook/wiki/wiki/PageNumberPrefixes#page-number-prefixes) has some errors. It can not be used at all.

**Comment by eduardtibet** [comment]
Thanks for the info. I'll try to fix it.

**Comment by eduardtibet** [comment]
Fixed. But take your attention that it is DocBook 4.5 (non-ns aware) stylesheet. Seems that it doesn't work with a DocBook 5.0/5.1 source files (there are no namespaces within matching templates).
